
package SIstemaDeGestion.Presentacion;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sistemagestionrecursoshumano.Departamento;
import sistemagestionrecursoshumano.SistemaRecursosHumanos;

/**
 *
 * @author juanc
 */
public class buscarDepartamento extends javax.swing.JDialog {

    private SistemaRecursosHumanos sistema;
    private VentanaPrincipal ventanaPrincipal;
    public buscarDepartamento(java.awt.Frame parent, boolean modal,SistemaRecursosHumanos sistema,VentanaPrincipal ventana) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            this.setIconImage(new ImageIcon(getClass().getResource("/SistemaDeGestion.images/CasaInicio.png")).getImage());
        } catch (Exception e) {
            System.out.println("Error en tiempo de ejecución ");
        }
        this.ventanaPrincipal=ventana;
        this.sistema=sistema;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtNombreDeparatmentobuscar = new javax.swing.JTextField();
        btnBuscarDepartamento = new javax.swing.JButton();
        BtnVolverMostrarDepartamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 220, 246));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel8.setText("SISTEMA DE RECURSOS HUMANOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Mostrar Departamento");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Nombre");

        TxtNombreDeparatmentobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreDeparatmentobuscarActionPerformed(evt);
            }
        });

        btnBuscarDepartamento.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnBuscarDepartamento.setText("Buscar");
        btnBuscarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDepartamentoActionPerformed(evt);
            }
        });

        BtnVolverMostrarDepartamento.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnVolverMostrarDepartamento.setText("Volver");
        BtnVolverMostrarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverMostrarDepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1)
                        .addGap(117, 117, 117)
                        .addComponent(TxtNombreDeparatmentobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnBuscarDepartamento)
                        .addGap(92, 92, 92)
                        .addComponent(BtnVolverMostrarDepartamento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtNombreDeparatmentobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarDepartamento)
                    .addComponent(BtnVolverMostrarDepartamento))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreDeparatmentobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreDeparatmentobuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreDeparatmentobuscarActionPerformed

    private void BtnVolverMostrarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverMostrarDepartamentoActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnVolverMostrarDepartamentoActionPerformed

    private void btnBuscarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDepartamentoActionPerformed
        String nombreBuscar=this.TxtNombreDeparatmentobuscar.getText().trim();
        Departamento p=this.sistema.buscarDepartamento(nombreBuscar);
        if (p== null){
           JOptionPane.showMessageDialog(this,"el producto "+nombreBuscar+ "No se encontro");
       }else{
            JOptionPane.showMessageDialog(this, "El Departamento fue encontrado: \n"
        + "Departamento: \n"
        + "Id:  " + p.getId() + ": " + p.getNombre() );
        }
     
    }//GEN-LAST:event_btnBuscarDepartamentoActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolverMostrarDepartamento;
    private javax.swing.JTextField TxtNombreDeparatmentobuscar;
    private javax.swing.JButton btnBuscarDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
